const COMMANDS={
 forward:{label:'↑ Move forward',short:'↑',class:'forward',help:'Moves Bolt ahead by one tile in the direction he is facing.'},
 left:{label:'↶ Turn left',short:'↶',class:'left',help:'Turns Bolt 90° left without moving to another tile.'},
 right:{label:'↷ Turn right',short:'↷',class:'right',help:'Turns Bolt 90° right without moving to another tile.'},
 loop:{label:'↻ Repeat',short:'↻',class:'loop',help:'Runs every block placed inside it several times. Example: Repeat 4 containing Move forward travels four tiles.'},
 ifpath:{label:'◇ If path ahead',short:'◇',class:'ifpath',help:'Checks Bolt’s sensor. Blocks in THEN run only when the next tile is clear.'},
 else:{label:'◇ Else',short:'⑂',class:'ifpath',help:'Adds an ELSE branch to an If block. Its blocks run when the path ahead is blocked.'},
 interact:{label:'✦ Interact',short:'✦',class:'interact',help:'Uses the object on Bolt’s current tile, such as collecting a battery or activating a switch.'}
};
const STAGES=[
 {title:'First Steps',concept:'SEQUENCES',story:'Help Bolt reach the charging station.',lesson:'Sequence',lessonText:'Computers follow commands in order, one step at a time.',hint:'Try three Move forward blocks.',size:[5,5],start:[4,0,1],goal:[4,3],walls:[[0,2],[1,2],[2,2]],tools:['forward'],ideal:3},
 {title:'Corner Course',concept:'DIRECTIONS',story:'Turn Bolt around the garden wall.',lesson:'Direction',lessonText:'Turns change which way Bolt faces. Then forward uses the new direction.',hint:'Move once, turn left, move twice, turn right, then move once.',size:[5,5],start:[4,0,1],goal:[2,2],walls:[[3,2],[4,3]],tools:['forward','left','right'],ideal:6},
 {title:'Repeat Retreat',concept:'LOOPS',story:'Climb the blocked staircase by finding the pattern that repeats.',lesson:'Loops',lessonText:'Loops can repeat a whole pattern of commands—not just one movement.',hint:'Repeat 4 times the sequence to get across one "stair".',size:[6,6],start:[5,0,1],goal:[1,4],walls:[[5,2],[5,3],[5,4],[5,5],[4,0],[4,3],[4,4],[4,5],[3,0],[3,1],[3,4],[3,5],[2,0],[2,1],[2,2],[2,5],[1,0],[1,1],[1,2],[1,3]],tools:['forward','left','right','loop'],ideal:5},
 {title:'Trail Scanner',concept:'CONDITIONS',story:'Use one smart rule repeatedly to navigate the bend.',lesson:'Conditions',lessonText:'If runs one group when something is true; Else runs another when it is false.',hint:'Repeat 5 times: IF the path is clear, move forward; ELSE, turn left.',size:[5,5],start:[4,0,1],goal:[2,2],walls:[[4,3],[3,0],[3,1]],tools:['forward','left','right','loop','ifpath','else'],ideal:4},
 {title:'Power Pickup',concept:'OBJECTS',story:'Collect the battery before reaching the station.',lesson:'Interaction',lessonText:'Programs can change the world by interacting with different tasks.',hint:'Reach and collect the battery, continue to the far-right path, then loop around the walls toward the goal.',size:[6,6],start:[5,0,1],goal:[2,3],object:[5,2],walls:[[4,2],[4,3],[3,4]],tools:['forward','left','right','loop','interact'],ideal:11},
 {title:'The Grand Circuit',concept:'CODE CHALLENGE',story:'Follow the service tunnel, activate the switch, and let Bolt’s sensor handle both bends.',lesson:'Algorithms',lessonText:'An algorithm combines sequence, loops, decisions, and actions to solve a goal.',hint:'Repeat forward twice and interact. Then repeat 8 times the if/else to follow the path.',size:[6,6],start:[5,0,1],goal:[1,2],object:[5,2],switch:true,walls:[[0,0],[0,1],[0,2],[0,3],[0,4],[0,5],[1,0],[1,1],[1,4],[1,5],[2,0],[2,1],[2,2],[2,4],[2,5],[3,0],[3,1],[3,2],[3,4],[3,5],[4,0],[4,1],[4,2],[4,4],[4,5],[5,4],[5,5]],tools:['forward','left','right','loop','ifpath','else','interact'],ideal:7}
];
let stage=0,program=[],robot={},running=false,activeId='',dragId='',collected=false,nextId=1,selected={list:program,label:'main program'},bestStars=JSON.parse(localStorage.getItem('roboBestStars')||'{}'),unlocked=Number(localStorage.getItem('roboUnlocked')||0);
const $=id=>document.getElementById(id),dirs=[[-1,0],[0,1],[1,0],[0,-1]],wait=ms=>new Promise(r=>setTimeout(r,ms));
function node(type){const n={id:'b'+nextId++,type};if(type==='loop'){n.count=2;n.body=[]}if(type==='ifpath'){n.then=[];n.else=null}return n}
function loadStage(i){stage=i;program=[];selected={list:program,label:'main program'};collected=false;const s=STAGES[i];robot={r:s.start[0],c:s.start[1],d:s.start[2]};$('title').textContent=s.title;$('concept').textContent=s.concept;$('story').textContent=s.story;$('lessonTitle').textContent='Coding idea: '+s.lesson;$('lessonText').textContent=s.lessonText;$('stageLabel').textContent=`Stage ${i+1} of ${STAGES.length}`;$('progressBar').style.width=((i+1)/STAGES.length*100)+'%';renderTools();renderProgram();renderMap();renderStages();message('Build a program to guide Bolt.')}
function renderMap(){const s=STAGES[stage],m=$('map');m.innerHTML='';m.style.gridTemplateColumns=`repeat(${s.size[1]},1fr)`;m.style.gridTemplateRows=`repeat(${s.size[0]},1fr)`;for(let r=0;r<s.size[0];r++)for(let c=0;c<s.size[1];c++){const t=document.createElement('div');t.className='tile';if(s.walls.some(x=>x[0]===r&&x[1]===c))t.classList.add('wall');if(s.goal[0]===r&&s.goal[1]===c)t.classList.add('goal');if(s.object&&!collected&&s.object[0]===r&&s.object[1]===c)t.classList.add(s.switch?'switch':'object');if(robot.r===r&&robot.c===c){const b=document.createElement('div');b.className='robot';b.textContent='◉';b.style.transform=`rotate(${robot.d*90}deg)`;t.appendChild(b)}m.appendChild(t)}}
function renderTools(){const box=$('toolbox');box.innerHTML='';STAGES[stage].tools.forEach(k=>{const b=document.createElement('button');b.className='command '+COMMANDS[k].class;b.textContent=COMMANDS[k].label;b.title=COMMANDS[k].help;b.onclick=()=>addBlock(k);box.appendChild(b)})}
function addBlock(type){if(running)return;if(type==='else'){const target=findLastIf(selected.list)||findLastIf(program);if(!target){message('Add an If block before adding Else.',true);return}target.else=[];selected={list:target.else,label:'ELSE branch'};renderProgram();message('Else added. New blocks will go inside ELSE.');return}if(countBlocks(program)>=30)return message('That program is full. Try using Repeat!',true);const n=node(type);selected.list.push(n);if(type==='loop')selected={list:n.body,label:'Repeat'};if(type==='ifpath')selected={list:n.then,label:'THEN branch'};renderProgram()}
function findLastIf(list){for(let i=list.length-1;i>=0;i--){if(list[i].type==='ifpath')return list[i]}return null}
function countBlocks(list){return list.reduce((n,b)=>n+1+(b.body?countBlocks(b.body):0)+(b.then?countBlocks(b.then):0)+(b.else?countBlocks(b.else):0),0)}
function selectList(list,label){selected={list,label};renderProgram();message(`Adding blocks to ${label}.`)}
function renderProgram(){const w=$('workspace');w.innerHTML='';w.onclick=e=>{if(!e.target.closest('.block-body')&&!e.target.closest('button,select')){selected={list:program,label:'main program'};renderProgram();message('New blocks will be added to the main program.')}};w.ondragover=e=>{if(e.target===w)e.preventDefault()};w.ondrop=e=>{if(e.target===w){e.preventDefault();moveBlock(dragId,program,program.length)}};if(!program.length){w.innerHTML='<div class="empty"><span>＋</span><b>Add blocks to begin</b><small>Tap a command above</small></div>';w.firstElementChild.onclick=()=>selectList(program,'main program');w.firstElementChild.ondragover=e=>e.preventDefault();w.firstElementChild.ondrop=e=>{e.preventDefault();moveBlock(dragId,program,0)};return}renderList(program,w);const note=document.createElement('div');note.className='target-note';note.textContent='New blocks go to: '+selected.label+' · drag blocks to rearrange';w.appendChild(note)}
function renderList(list,parent){list.forEach((cmd,i)=>{const b=document.createElement('div');b.className='block '+COMMANDS[cmd.type].class+(cmd.body||cmd.then?' container-block':'')+(cmd.id===activeId?' active':'');b.draggable=!running;b.dataset.blockId=cmd.id;b.ondragstart=e=>{dragId=cmd.id;b.classList.add('dragging');e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',cmd.id)};b.ondragend=()=>{dragId='';b.classList.remove('dragging')};b.ondragover=e=>{e.preventDefault();e.stopPropagation();b.classList.add('drop-before')};b.ondragleave=()=>b.classList.remove('drop-before');b.ondrop=e=>{e.preventDefault();e.stopPropagation();b.classList.remove('drop-before');moveBlock(dragId,list,i)};const row=document.createElement('div');row.className='block-row';row.innerHTML=`<span class="drag-handle" title="Drag to rearrange">⠿</span><span>${COMMANDS[cmd.type].short}</span><b>${COMMANDS[cmd.type].label.replace(/^[^ ]+ /,'')}</b>${cmd.type==='loop'?`<select aria-label="repeat count">${[2,3,4,5,6,7,8].map(n=>`<option ${cmd.count===n?'selected':''}>${n} times</option>`).join('')}</select>`:''}<button class="remove-block" aria-label="remove">×</button>`;const sel=row.querySelector('select');if(sel)sel.onchange=e=>cmd.count=Number(e.target.value.split(' ')[0]);row.querySelector('.remove-block').onclick=e=>{e.stopPropagation();list.splice(i,1);selected={list:program,label:'main program'};renderProgram()};b.appendChild(row);if(cmd.type==='loop')appendBranch(b,cmd.body,'REPEAT THESE BLOCKS','Repeat',false,cmd);if(cmd.type==='ifpath'){appendBranch(b,cmd.then,'THEN · PATH IS CLEAR','THEN branch',false,cmd);if(cmd.else)appendBranch(b,cmd.else,'ELSE · PATH IS BLOCKED','ELSE branch',true,cmd);else{const add=document.createElement('button');add.className='add-else';add.textContent='+ Add Else branch';add.onclick=()=>{cmd.else=[];selectList(cmd.else,'ELSE branch')};b.appendChild(add)}}parent.appendChild(b)})}
function appendBranch(block,list,label,targetLabel,isElse=false,owner){const lab=document.createElement('span');lab.className='branch-label';lab.textContent=label;block.appendChild(lab);const body=document.createElement('div');body.className='block-body'+(isElse?' else-body':'')+(selected.list===list?' selected':'');body.onclick=e=>{if(e.target===body||e.target.classList.contains('nest-empty')){e.stopPropagation();selectList(list,targetLabel)}};body.ondragover=e=>{e.preventDefault();e.stopPropagation();body.classList.add('drop-target')};body.ondragleave=()=>body.classList.remove('drop-target');body.ondrop=e=>{e.preventDefault();e.stopPropagation();body.classList.remove('drop-target');if(dragId!==owner.id&&!nodeContains(dragId,owner))moveBlock(dragId,list,list.length)};if(list.length)renderList(list,body);else body.innerHTML='<div class="nest-empty">Tap or drag blocks here</div>';block.appendChild(body)}
function takeBlock(id,list=program){for(let i=0;i<list.length;i++){if(list[i].id===id)return list.splice(i,1)[0];for(const child of [list[i].body,list[i].then,list[i].else])if(child){const found=takeBlock(id,child);if(found)return found}}return null}
function findNode(id,list=program){for(const n of list){if(n.id===id)return n;for(const child of [n.body,n.then,n.else])if(child){const found=findNode(id,child);if(found)return found}}return null}
function nodeContains(id,owner){return [owner.body,owner.then,owner.else].filter(Boolean).some(list=>!!findNode(id,list))}
function ownsList(node,target){for(const list of [node.body,node.then,node.else].filter(Boolean)){if(list===target)return true;for(const child of list)if(ownsList(child,target))return true}return false}
function findLocation(id,list=program){for(let i=0;i<list.length;i++){if(list[i].id===id)return{list,index:i};for(const child of [list[i].body,list[i].then,list[i].else])if(child){const found=findLocation(id,child);if(found)return found}}return null}
function moveBlock(id,target,index){if(!id)return;const moving=findNode(id),source=findLocation(id);if(!moving||!source||ownsList(moving,target))return;if(source.list===target&&source.index<index)index--;const block=source.list.splice(source.index,1)[0];target.splice(Math.min(index,target.length),0,block);selected={list:program,label:'main program'};renderProgram()}
function reset(){const s=STAGES[stage];robot={r:s.start[0],c:s.start[1],d:s.start[2]};collected=false;activeId='';renderMap();renderProgram();message('Bolt is back at the start.')}
function canMove(){const s=STAGES[stage],nr=robot.r+dirs[robot.d][0],nc=robot.c+dirs[robot.d][1];return nr>=0&&nc>=0&&nr<s.size[0]&&nc<s.size[1]&&!s.walls.some(x=>x[0]===nr&&x[1]===nc)}
function action(cmd){if(cmd.type==='left')robot.d=(robot.d+3)%4;else if(cmd.type==='right')robot.d=(robot.d+1)%4;else if(cmd.type==='forward'){if(!canMove())return false;robot.r+=dirs[robot.d][0];robot.c+=dirs[robot.d][1]}else if(cmd.type==='interact'){const o=STAGES[stage].object;if(o&&robot.r===o[0]&&robot.c===o[1])collected=true;else return false}renderMap();return true}
async function execute(list){for(const cmd of list){activeId=cmd.id;renderProgram();let ok=true;if(cmd.type==='loop'){for(let n=0;n<cmd.count&&ok;n++)ok=await execute(cmd.body)}else if(cmd.type==='ifpath')ok=await execute(canMove()?cmd.then:(cmd.else||[]));else{ok=action(cmd);await wait(380)}if(!ok)return false}return true}
async function run(){if(running||!program.length)return;reset();running=true;message('Bolt is following your code…');const ok=await execute(program);running=false;activeId='';renderProgram();if(!ok)return message('Bolt could not complete that block. Check for walls and objects.',true);checkWin()}
function totalStars(){return Object.values(bestStars).reduce((sum,n)=>sum+Number(n),0)}
function checkWin(){const s=STAGES[stage];if(robot.r!==s.goal[0]||robot.c!==s.goal[1]||(s.object&&!collected)){message(s.object&&!collected?'The object still needs to be activated.':'Not at the goal yet. Adjust your blocks and try again.',true);return}const blocks=countBlocks(program),earned=blocks<=s.ideal?3:blocks<=s.ideal+2?2:1,old=Number(bestStars[stage]||0);bestStars[stage]=Math.max(old,earned);localStorage.setItem('roboBestStars',JSON.stringify(bestStars));unlocked=Math.max(unlocked,Math.min(STAGES.length-1,stage+1));localStorage.setItem('roboUnlocked',unlocked);$('starCount').textContent=totalStars();const missed=STAGES.map((item,i)=>({item,i,stars:Number(bestStars[i]||0)})).filter(x=>x.stars<3),allComplete=STAGES.every((_,i)=>Number(bestStars[i]||0)>0);if(allComplete){$('winEyebrow').textContent=missed.length?'QUEST COMPLETE':'PERFECT SCORE';$('winTitle').textContent=missed.length?'Every mission complete!':'You earned every star!';$('earned').textContent=`★ ${totalStars()} / ${STAGES.length*3}`;if(missed.length){const next=missed[0];$('winCopy').textContent=`Amazing work—Bolt reached every destination. Replay ${next.item.title} to collect ${3-next.stars} missed ${3-next.stars===1?'star':'stars'}.`;$('nextBtn').textContent=`Replay ${next.item.title} →`;$('nextBtn').dataset.nextStage=next.i}else{$('winCopy').textContent='Incredible! You solved every coding challenge with a three-star solution. Bolt is a master navigator—and you are a master coder!';$('nextBtn').textContent='Play again from Stage 1 →';$('nextBtn').dataset.nextStage=0}}else{$('winEyebrow').textContent='MISSION COMPLETE';$('winTitle').textContent='Brilliant coding!';$('earned').textContent='★'.repeat(earned)+'☆'.repeat(3-earned);$('winCopy').textContent=`Bolt made it with ${blocks} blocks. ${earned>old?'New best solution!':`Your best for this stage is ${bestStars[stage]} stars.`}`;$('nextBtn').textContent='Next mission →';$('nextBtn').dataset.nextStage=Math.min(stage+1,STAGES.length-1)}$('winModal').classList.remove('hidden');renderStages();message(allComplete?'All stages complete!':'Mission complete!',false,true)}
function message(text,error=false,success=false){const f=$('feedback');f.textContent=text;f.className='feedback'+(error?' error':success?' success':'')}
function renderStages(){const menu=$('stageMenu');menu.innerHTML='';STAGES.forEach((s,i)=>{const b=document.createElement('button');b.className=i===stage?'active':'';b.disabled=i>unlocked;const best=Number(bestStars[i]||0);b.textContent=`${best?'★'.repeat(best):i>unlocked?'🔒':i+1}  ${s.title}`;b.onclick=()=>{loadStage(i);menu.classList.add('hidden')};menu.appendChild(b)})}
function renderGuide(){const list=$('guideList');list.innerHTML='';Object.entries(COMMANDS).forEach(([key,c])=>{const item=document.createElement('div');item.className='guide-item';item.innerHTML=`<span class="guide-icon ${c.class}">${c.short}</span><div><b>${c.label.replace(/^[^ ]+ /,'')}</b><p>${c.help}</p></div>`;list.appendChild(item)})}
$('runBtn').onclick=run;$('stepBtn').onclick=()=>message('Step mode is unavailable for nested blocks; use Run to see the whole decision.');$('resetBtn').onclick=reset;$('clearBtn').onclick=()=>{if(!running){program=[];selected={list:program,label:'main program'};renderProgram();message('Workspace cleared.')}};$('hintBtn').onclick=()=>message('Hint: '+STAGES[stage].hint);$('stagePicker').onclick=()=>$('stageMenu').classList.toggle('hidden');$('nextBtn').onclick=()=>{$('winModal').classList.add('hidden');loadStage(Number($('nextBtn').dataset.nextStage||0))};$('guideBtn').onclick=()=>$('guideModal').classList.remove('hidden');$('closeGuide').onclick=()=>$('guideModal').classList.add('hidden');$('guideModal').onclick=e=>{if(e.target===$('guideModal'))$('guideModal').classList.add('hidden')};$('starCount').textContent=totalStars();renderGuide();loadStage(0);
